data:
  in_memory: 1
  num_workers: 12
  train_dataset: "/export/work/cbotos/imagenet/train_500_0.50_90.ffcv"
  val_dataset: "/export/work/cbotos/imagenet/val_500_0.50_90.ffcv"
dist:
  world_size: 8
logging:
  folder: /tmp/
lr:
  lr: 1.7
  lr_schedule_type: cyclic
model:
  arch: resnet50
resolution:
  end_ramp: 76
  max_res: 192
  min_res: 160
  start_ramp: 65
training:
  eval_only: 1
  batch_size: 512
  bn_wd: 0
  distributed: 0
  epochs: 88
  label_smoothing: 0.1
  momentum: 0.9
  optimizer: sgd
  weight_decay: 0.0001
  use_blurpool: 1
validation:
  lr_tta: true
  resolution: 256
